---
title: "Sanitary Violations: Final Project"
author: "Steven Espinoza"
date: "11/27/2018"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(shiny)
library(leaflet)
library(plotly)
library(lubridate)
library(stringr)
library(janitor)
library(RSocrata)
library(tidyverse)
library(kableExtra)
```

```{r loading_data, include=FALSE}
# Loading in the data from the API
df <- read.socrata("https://data.cambridgema.gov/resource/3c3f-byi2.csv")

# Making new columns for 'lat' and 'lng' and the difference in days between corrected_date - cited_date
df <- df %>% 
  separate(address, into = c('point', 'lng', 'lat'), sep = ' ') %>% 
  select(-point) %>% 
  
  # New column for lats and longs
  mutate(lng = gsub('\\(', "", lng), lat = gsub('\\)', "", lat)) %>% 
  
  # New column for time difference
  mutate(corrected_time = seconds_to_period(corrected_date - cited_date)$day)
```

```{r cleaning_names, include=FALSE}
# Cleaning the "establishment names" column:
# A lot of the establishment names did not match perfectly in the dataset. For example, a restaurant like "Ihop" was coded as "I hop", "IHOP", and "I-Hop", leading to three distinct ways to describe only one restaurant. I first thought that the best way to fix this would be to create a unique identifier for this by first removing all spaces, dashes, and some other characters for the establishment names, and then combining the first three letters of this new variable with the address (note: addresses weren't as inconsistent as the establishment names). I figured that if the address and the first three letters matched they would be describing the same place.

# First step: creating a new column for a "unique ID" of each location
# Starting off by making all establishment names and addresses uppercase for sake of consistency. 
df <- df %>% 
  mutate(unique_id = toupper(establishment_name), address_address = toupper(address_address))

# Next step: removing all apostrophes, periods, dashes, and spaces for establishment names
df$unique_id = gsub("'", "", df$unique_id)
df$unique_id = gsub("’", "", df$unique_id)
df$unique_id = gsub("/.", "", df$unique_id)
df$unique_id = gsub(" ", "", df$unique_id)
df$unique_id = gsub("-", "", df$unique_id)

# Creating our 'unique_id': a combination of the address listed and the first three letters of the restaurant
df <- df %>% 
  mutate(unique_id = paste(address_address, substr(unique_id, 1, 3)))

# Continuing the matching process: creating a new data frame to create a list of "accurate" establishment names
df_ <- df

# Make the "accurate" establishment name equivalent to the first instance of that name
df_ <- df_ %>% 
  group_by(unique_id) %>% 
  summarize(first_estab = establishment_name[1])

df2 <- df

# Join the datasets together in order to have the unique ID and the "first_estab" column, which creates the "accurate" names column I was hoping for
joined <- left_join(df_, df2, 'unique_id') %>% as.data.frame()

# My goal is to restrict the dataset to establishments I've made my own list for around Harvard Square. This could be done by filtering for latitudes/longitudes within a specific area around Harvard Square. This reduces the number of observations from about 30,000 to about 4,000, making it much easier for me to inspect and clean as I go along.
joined <- joined %>% 
  filter(lat >= 42.368694) %>% 
  filter(lat <= 42.376375) %>% 
  filter(lng <= -71.125129) %>% 
  filter(lng >= -71.112232) %>% 
  as.data.frame()


# Next step: Look at unique "first_estab" names and see if they are all genuinely unique. Ideally there'd be no mistakes.
sort(unique(joined$first_estab))

# Fixing mistakes: This unfortunately has to be done by hand. Thankfully there are only about 250 unique first_estab names on the list, making it easy for me to sort the list alphabetically and find any mismatches.

# Mistake #1: Al's Harvard Square Cafe seems to have two different addresses, even though they have the same lat, lng values. Fixing this.
joined$first_estab[joined$first_estab == "Al\'s"] <- "Al's Harvard Square Cafe"

# Mistake #2: Au Bon Pain
joined$first_estab[joined$first_estab == "Au Bon pain"] <- "Au Bon Pain"

# Mistake #3: Beat Hotel
joined$first_estab[joined$first_estab == "Beat hotel"] <- "Beat Hotel"

# Mistake #4: b.good versus bgood
joined$first_estab[joined$first_estab == "bgood"] <- "b.good"

# Mistake #5: Charlie's Kitchen versus Charlie's Kitchen/red House
joined$first_estab[joined$first_estab == "Charlie\'s Kitchen/red House"] <- "Charlie\'s Kitchen"

# Mistake #6: Clover versus Clover Fast Food (judged to be the same one by the way--on 1326 Massachusetts Ave)
joined$first_estab[joined$first_estab == "Clover Fast Food"] <- "Clover"

# Mistake #7: CVS versus CVS Pharmacy #240. "CVS" refers to the one next to Otto's that's now closed, while "CVS Pharmacy #240" refers to the one right on the square.
joined$first_estab[joined$first_estab == "CVS"] <- "CVS (Next to Otto\'s)"
joined$first_estab[joined$first_estab == "CVS Pharmacy #240"] <- "CVS (Next to T stop)"

# Mistake #8: correcting Dophin (misspelled "Dolphin")
joined$first_estab[joined$first_estab == "Dophin"] <- "Dolphin"

# Mistake #9: CRLS (means "Cambridge Rindge & Latin High School-CRLS")
joined$first_estab[joined$first_estab == "CRLS"] <- "Cambridge Rindge & Latin High School-CRLS"

# Mistake #10: IHOP versus IHop
joined$first_estab[joined$first_estab == "IHop"] <- "IHOP"

# Mistake #11: J.P. Licks versus JP Licks
joined$first_estab[joined$first_estab == "JP Licks"] <- "J.P. Licks"
joined$first_estab[joined$first_estab == "J.P. Licks"] <- "JP Licks"

# Mistake #12: Lamont Library Cafe verus HUDS Lamont Library Cafe
joined$first_estab[joined$first_estab == "HUDS Lamont Library Cafe"] <- "Lamont Library Cafe"

# Mistake #13: Legal Sea Foods versus Legal Seafood.
joined$first_estab[joined$first_estab == "Legal Seafood."] <- "Legal Sea Foods"

# Mistake #14: variations of Mr. Bartley's
joined$first_estab[joined$first_estab == "Mr Bartley\'s Gourmet Burger"] <- "Mr. Bartley\'s Burger Cottage"
joined$first_estab[joined$first_estab == "Bartley\'s Burgers"] <- "Mr. Bartley\'s Burger Cottage"

# Mistake #15: Oggi  's versus Oggi Gourmet
joined$first_estab[joined$first_estab == "Oggi \'s"] <- "Oggi Gourmet"

# Mistake #16: Qdoba versus Qdoba Mexican Grill #2429 (both refer to the same Qdoba on mass ave)
joined$first_estab[joined$first_estab == "Qdoba Mexican Grill #2429"] <- "Qdoba"

# Mistake #17: Fixing 'The Charles Hotel/Henrietta's Table"
joined$first_estab[joined$first_estab == "The Charles Hotel/Henrietta\'s Table"] <- "Henrietta\'s Table"

# Mistake #18: "The Maharaja" versus "Maharaja"
joined$first_estab[joined$first_estab == "The Maharaja"] <- "Maharaja"

# Mistake #19: Signet Society versus The Signet Society
joined$first_estab[joined$first_estab == "The Signet Society"] <- "Signet Society"

# Mistake #20: capitalizing "Gutman Cafe"
joined$first_estab[joined$first_estab == "Gutman cafe"] <- "Gutman Cafe"

# Mistake #21: fixing "HUDS Annenberg Dining Hall" and calling it "Annenberg Dining Hall"
joined$first_estab[joined$first_estab == "HUDS Annenberg Dining Hall"] <- "Annenberg Dining Hall"

# Mistake #22: The Chauhaus at the GSD
joined$first_estab[joined$first_estab == "ChauHaus at GSD"] <- "HUDS Chauhaus"

# Mistake #23: Shabu shabu
joined$first_estab[joined$first_estab == "Shabu shabu"] <- "Shabu Shabu"

# Mistake #22: Tamirind BAy
joined$first_estab[joined$first_estab == "Tamirind BAy"] <- "Tamirind Bay"

# Mistake #23: Adams House Dining
joined$first_estab[joined$first_estab == "Adams House"] <- "HUDS Adams Dining"

# Mistake #24: Leverett Dining Hall
joined$first_estab[joined$first_estab == "Leverett Dining Hall"] <- "HUDS Leverett"

# Mistake #25: Lowell/Winthrop Dining Halls
joined$first_estab[joined$first_estab == "Lowell/Winthrop Dining Halls"] <- "HUDS Lowell/Winthrop Dining Halls"

# Mistake #26: They misspelled CGIS as "CJIS" -_-
joined$first_estab[joined$first_estab == "HUDS CJIS Cafe"] <- "HUDS CGIS Cafe"

# Mistake #27: adding "HUDS" in front of "Quincy House" and "Quincy Grill" for consistency
joined$first_estab[joined$first_estab == "Quincy House"] <- "HUDS Quincy House"
joined$first_estab[joined$first_estab == "Quincy Grill"] <- "HUDS Quincy Grill"

# Mistake #28: The Commons at Gutman Library (with HUDS in front)
joined$first_estab[joined$first_estab == "The Commons at Gutman Library"] <- "HUDS Gutman Library Cafe"
joined$first_estab[joined$first_estab == "Gutman Cafe"] <- "HUDS Gutman Library Cafe"

# Mistake #29: "University Lutheran church"
joined$first_estab[joined$first_estab == "University Lutheran church"] <- "University Lutheran Church"

# Mistake #30: Lamont Cafe
joined$first_estab[joined$first_estab == "Lamont Library Cafe"] <- "HUDS Lamont Library Cafe"

# Mistake #31: "Harvard Center for Gov&International Studies"
joined$first_estab[joined$first_estab == "Harvard Center for Gov&International Studies"] <- "HUDS CGIS Cafe"

# Mistake #32: adding more info to the different Starbucks locations in the dataset
joined$first_estab[joined$unique_id == "1380 MASSACHUSETTS AVE STA"] <- "Starbucks (Harvard Square)"
joined$first_estab[joined$unique_id == "1384 MASSACHUSETTS AVE STA"] <- "Starbucks (Harvard Square)"
joined$first_estab[joined$unique_id == "36 JFK ST STA"] <- "Starbucks (Garage)"
joined$first_estab[joined$unique_id == "468 BROADWAY STA"] <- "Starbucks (Broadway)"
joined$first_estab[joined$unique_id == "31 CHURCH ST STA"] <- "Starbucks (Church St)"

# Mistake #33: Differentiating between the different Dunkin Donuts
joined$first_estab[joined$unique_id == "1 ELIOT ST DUN"] <- "Dunkin Donuts (JFK Street)"
joined$first_estab[joined$unique_id == "65 JFK ST DUN"] <- "Dunkin Donuts (JFK Street)"
joined$first_estab[joined$unique_id == "61 CHURCH ST DUN"] <- "Dunkin Donuts (Church St)"
joined$first_estab[joined$unique_id == "1400 MASSACHUSETTS AVE DUN"] <- "Dunkin Donuts (Harvard COOP)"

# Mistake #44: differentiating between the different Peets Coffees
joined$first_estab[joined$unique_id == "100 MT AUBURN ST PEE"] <- "Peets Coffee & Tea (Winthrop Square)"
joined$first_estab[joined$unique_id == "24 JFK ST PEE"] <- "Peets Coffee & Tea (Capital One)"

# Mistake #45: they actually said "swing house" referring to Lowell now (same address)
joined$first_estab[joined$unique_id == "1201 MASSACHUSETTS AVE HAR"] <- "HUDS Swing House"
joined$first_estab[joined$first_estab == "SWING dorm"] <- "HUDS Swing House"

# Mistake #46: fixing the Au Bon Pains
joined$first_estab[joined$unique_id == "1100 MASSACHUSETTS AVE AUB"] <- "Au Bon Pain (Mass Ave)"
joined$first_estab[joined$unique_id == "124 MT AUBURN ST AUB"] <- "Au Bon Pain (Mount Auburn St)"
joined$first_estab[joined$unique_id == "1350 MASSACHUSETTS AVE AUB"] <- "Au Bon Pain (Out-of-business)"
joined$first_estab[joined$unique_id == "1360 MASSACHUSETTS AVE AUB"] <- "Au Bon Pain (Out-of-business)"

# Mistake #47: Fixing more capitalization to make the list look pretty
joined$first_estab[joined$first_estab == "Cambridge Center for adult education"] <- "Cambridge Center for Adult Education"

# Mistake #48: Hourly
joined$first_estab[joined$first_estab == "The Hourly Oyster House"] <- "The Hourly Oyster House"


# Next step: read the cleaned "joined" dataframe as RDS to make shiny app.
write_rds(joined, path='final_project/data.rds')
```


```{r first_tab, include=FALSE}
# Testing out graphics that I use on the Shiny app will be done in this code chunk.

# First graphic: line chart: sanitary violations for a specific establishment over time
joined %>% 
  filter(first_estab == 'Cabot\'s Candy') %>% 
  mutate(year_cited = as.Date(cited_date)) %>% 
  count(year_cited) %>% 
  plot_ly(x = ~year_cited, y = ~n, type = 'scatter', mode = 'lines') %>% 
  layout(title = paste('Sanitary Violations Over Time For', 'Felipe\'s Taqueria'),
         xaxis = list(title = 'Year'),
         yaxis = list(title = 'Number of Violations'))

# Second graphic: Location
joined %>% 
  filter(first_estab == 'Felipe\'s Taqueria') %>%
  as.tibble() %>%
  mutate(lng = as.numeric(as.character(lng))) %>% 
  mutate(lat = as.numeric(as.character(lat))) %>% 
  head(1) %>% 
  leaflet() %>% 
  addProviderTiles('CartoDB',
                   options = providerTileOptions(minZoom = 16, maxZoom = 18)) %>% 
  addPopups(~lng, ~lat, "hello")

# Third graphic: Kable output
joined %>% 
  filter(first_estab == 'Felipe\'s Taqueria') %>% 
  mutate(corrected_date = as.Date(corrected_date)) %>% 
  select(first_estab, cited_date, corrected_date, code_description) %>% 
  kable(col.names = c('Name', 'Date Cited', 'Date Corrected', 'Description'), escape=F) %>%
  kable_styling() %>%
  scroll_box(width = "100%", height = "400px")

```

```{r tab_2}
# Making a line graph with two lines showing both of the establishments selected
joined %>% 
  filter(first_estab == 'Felipe\'s Taqueria' | first_estab == 'El Jefe\'s Taqueria') %>% 
  mutate(year_cited = as.Date(cited_date)) %>% 
  count(first_estab, year_cited) %>% 
  plot_ly(x = ~year_cited, y = ~n, type = 'scatter', mode = 'lines', color = ~first_estab) %>% 
  layout(xaxis = list(title = 'Date'), yaxis = list(title = 'Number of Violations'))
  
# Making a bar graph comparing both establishments overall, or for a specific violation
joined %>% 
  filter(first_estab == 'Felipe\'s Taqueria' | first_estab == 'El Jefe\'s Taqueria') %>% 
  mutate(year_cited = as.Date(cited_date)) %>% 
  count(first_estab, year_cited) %>% 
  group_by(first_estab) %>% 
  summarize(sum = sum(n)) %>% 
  plot_ly(x = ~first_estab, y = ~sum, type = 'bar', color = ~first_estab) %>% 
  layout(xaxis = list(title = 'Establishment'), 
         yaxis = list(title = 'Number of Violations'),
         showlegend = FALSE)
```

```{r tab_3}
# Summarizing the worst sanitary violators around Harvard Square with a dot map, with the radius of the dot signifying how many violations the establishment has either overall or for a specific sanitary violation

# First: thinking if "All" is selected
# Step 1: Make a list of all unique first_estabs with corresponding lat, lng values
coords <- joined %>% 
  group_by(first_estab) %>% 
  summarize(lat = lat[1], lng = lng[1])

# Step 2: Make a list of the worst violators
worst <- joined %>% 
  mutate(year_cited = as.Date(cited_date)) %>%
  count(first_estab, year_cited) %>% 
  group_by(first_estab) %>% 
  summarize(sum = sum(n)) %>% 
  arrange(desc(sum)) %>% 
  head(20)

# Step 3: left_join to get lat, lng coordinates
join_summarize <- left_join(coords, worst, 'first_estab') %>% 
  filter(!is.na(sum)) %>% 
  arrange(desc(sum)) %>% 
  mutate(lat = as.numeric(as.character(lat)), lng = as.numeric(as.character(lng)))

# Step 4: Use the last dataframe to make a map showing the worst violators in Cambridge
join_summarize %>% 
  leaflet() %>% 
  addProviderTiles('CartoDB') %>% 
  addCircleMarkers(lng = ~lng, lat = ~lat,
                   radius = ~sum/7,
                   color = "red",
                   popup = ~paste("<b>", 
                                  first_estab, 
                                  "</b>: ", 
                                  sum, 
                                  " violations",
                                  sep = ''),
                   fillOpacity = 0.75)
  
  
# Second: thinking if a specific violation is selected, such as "Insects, Rodents, Animals, Outer Openings"


```






